import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      keyframes: {
        'datacamp-scroll': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
      },
      animation: {
        'datacamp-scroll': 'datacamp-scroll 35s linear infinite',
        blink: 'blink 0.8s step-start infinite',
      },
      colors: {
        'tertiary-container': '#919090',
        'on-secondary-container': '#e4e2e1',
        'on-primary-fixed': '#ffffff',
        'secondary-fixed-dim': '#adabaa',
        'surface-container-highest': '#353534',
        'tertiary-fixed-dim': '#474747',
        primary: '#ffffff',
        'on-error': '#690005',
        'on-secondary-fixed': '#1b1c1c',
        'on-surface': '#e5e2e1',
        tertiary: '#e4e2e1',
        'on-error-container': '#ffdad6',
        'surface-bright': '#3a3939',
        'surface-container-high': '#2a2a2a',
        'on-tertiary-container': '#000000',
        'on-tertiary-fixed-variant': '#e4e2e1',
        background: '#131313',
        'primary-fixed': '#5d5f5f',
        outline: '#919191',
        'error-container': '#93000a',
        'on-tertiary': '#1b1c1c',
        'on-primary-container': '#000000',
        'surface-container-low': '#1c1b1b',
        error: '#ffb4ab',
        'surface-tint': '#c6c6c7',
        'surface-container-lowest': '#0e0e0e',
        'surface-container': '#201f1f',
        'primary-fixed-dim': '#454747',
        'on-secondary-fixed-variant': '#3c3b3b',
        'tertiary-fixed': '#5f5e5e',
        'on-surface-variant': '#c6c6c6',
        'on-background': '#e5e2e1',
        'on-primary-fixed-variant': '#e2e2e2',
        secondary: '#c8c6c5',
        'inverse-on-surface': '#313030',
        'on-secondary': '#1b1c1c',
        'inverse-primary': '#5d5f5f',
        'on-tertiary-fixed': '#ffffff',
        'on-primary': '#1a1c1c',
        'inverse-surface': '#e5e2e1',
        'secondary-fixed': '#c8c6c5',
        'secondary-container': '#474746',
        'primary-container': '#d4d4d4',
        'outline-variant': '#474747',
        'surface-variant': '#353534',
        surface: '#131313',
        'surface-dim': '#131313',
        'accent-green': '#BBF7D0',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter'],
        body: ['Inter'],
        label: ['Inter'],
      },
    },
  },
  plugins: [],
}

export default config
